### ISSUE TITLE
Invalid `.stylelintrc.json` causes `dev` to hang

### ISSUE THREAD

**Issue by thommyhh** [pangolinjs/core#25]
I just found out, that an invalid `.stylelintrc.json` causes the `dev` task to hang. No error is printed, it just hangs. Invalid means in this case a missing comma, at the end of a line. When starting the `build` task the following error is printed out, which actually somehow points in the right direction.

```
(node:27) UnhandledPromiseRejectionWarning: JSONError: JSON Error in /build/frontend/.stylelintrc.json:
Unexpected string in JSON at position 796 while parsing '{	"extends": "stylelint-config-sass-gui'
    at module.exports (/build/frontend/node_modules/cosmiconfig/node_modules/parse-json/index.js:26:19)
    at loadJson (/build/frontend/node_modules/cosmiconfig/dist/loaders.js:14:12)
    at Explorer.loadFileContent (/build/frontend/node_modules/cosmiconfig/dist/createExplorer.js:226:12)
    at Promise.resolve.then (/build/frontend/node_modules/cosmiconfig/dist/createExplorer.js:248:21)
    at <anonymous>
(node:27) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:27) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Done in 9.72s.
```
The command is run inside a docker container with NodeJS v8.11.3 and Yarn 1.6.0.

**Comment by mvsde** [comment]
Unfortunately this is a problem with stylelint itself. eslint has the same issue with an invalid `.eslintrc.json`. Let's not write invalid JSON 😃
