### ISSUE TITLE
Do not hide error wrong config

### ISSUE THREAD

**Issue by thommyhh** [pangolinjs/core#40]
Please output any exception that might be thrown when requiring `pangolin.config.js` in `get-config.js` ll. 17 - 21. This will make it easier to find issues with an invalid configuration.

**Comment by mvsde** [comment]
The only error that might be thrown while requiring `pangolin.config.js` is a "not found" error. In this case the default config will be used. There are no checks if the provided user config is valid. It will be merged into the default config without asking any questions (which is definitely something that has to be improved).

So logging any errors would only result in something like this:

```
{ Error: Cannot find module '/Users/fynn/Projects/pangolinjs/core/test/project/pangolin.config.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:668:15)
    at Function.Module._load (internal/modules/cjs/loader.js:591:27)
    at Module.require (internal/modules/cjs/loader.js:723:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at module.exports (/Users/fynn/Projects/pangolinjs/core/lib/utils/get-config.js:32:24)
    at Object.exports.setup (/Users/fynn/Projects/pangolinjs/core/lib/store.js:15:18)
    at module.exports (/Users/fynn/Projects/pangolinjs/core/lib/commands/dev.js:24:9)
    at Command.program.command.description.option.option.option.action.env (/Users/fynn/Projects/pangolinjs/core/bin/pangolin-core.js:19:35)
    at Command.listener (/Users/fynn/Projects/pangolinjs/core/node_modules/commander/index.js:315:8)
    at Command.emit (events.js:193:13) code: 'MODULE_NOT_FOUND' }
```
